server:
  disable: true
  
positions:
  filename: c:/tmp/positions.yaml # This folder location must be created on disk prior to starting Promtail Windows service.

clients:
  - url: https://<username>:<password>@<loki host address>:<loki reverse proxy port>/loki/api/v1/push # e.g. https://username:password@hostaddress.com:2100/loki/api/v1/push
         
scrape_configs:      
- job_name: ApiGateway
  pipeline_stages:
  - json:
      expressions:
        Timestamp: '"@t"'
  - timestamp:
      source: Timestamp
      format: RFC3339Nano
  - match:
      selector: '{job="flows"}|~ "\"SourceContext\":.?\"Cortex[.]ServiceFabric[.]Service[.]ApiGateway\""'
      stages:
      - json:
          expressions:
            Type: Event.LogType || 'Cortex'
            Api: Event.Type
            Result: Event.Tags.Cortex.Result || 'Success'
            StatusCode: Event.Tags.Cortex."Http.Response.StatusCode" || Event.Details.Response.StatusCode || 'Unknown'
            Tenant: Event.Tags.Cortex."Tenant.Name" || Event.Details.Request.Inputs.tenant || 'Unknown'
            System: Event.Tags.Cortex."System.Name" || Event.Details.Request.Inputs.system || 'Unknown'
            Node: Event.Platform.Node.Name || Event.Service.NodeName || 'Unknown'
            PackageName: Event.Tags.Cortex."Package.Name" || Event.Details.Request.Inputs.packageName || 'Unknown'
            FlowName: Event.Tags.Cortex."Flow.Name" || Event.Details.Request.Inputs.flowName || 'Unknown'
            InitiatorIpAddress: Event.Details.Request.Initiator.IpAddress || 'Unknown'
            RequestStatus: '"@l"'
            Async: Event.Details.Request.Inputs.async || 'false'
      - labels:
          Type:
          Api:
          Result:
          StatusCode:
          Tenant:
          System:
          Node:
          PackageName: 
          FlowName:
          InitiatorIpAddress:
          RequestStatus:
          Async:
  - match:
      selector: '{job="flows"}|~ "\"Outputs\":.?null"'
      stages:
      - json:
          expressions:
            Result: Event.Tags.Cortex.Result || 'Unknown'
      - labels:
          Result:
  - match:
      selector: '{job="flows"}|~ "\"\\$type\":\"[.0-9a-zA-Z_, -]*ProblemDetails"'
      stages:
      - json:
          expressions:
            Result: Event.Tags.Cortex.Result || Event.Details.Response.Outputs.Value.Title || 'Not Set'
      - labels:
          Result:          
  static_configs:
  - targets:
      - localhost
    labels:
      job: flows
      __path__: "C:/ProgramData/Cortex/API Gateway Service/Logs/**/ServiceFabricHttpEventLog-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]{_[0-9][0-9][0-9],}.json" # This path must much the location to which logs of the API Gateway Service are written to. Glob syntax and pattern matching is supported, see https://github.com/bmatcuk/doublestar. 
