{
 "title": "Flow Execution Requests",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Tenant",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\"}, Tenant)"
   },
   {
    "name": "System",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\"}, System)"
   },
   {
    "name": "Node",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\"}, Node)"
   },
   {
    "name": "PackageName",
    "label": "Package Name",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\"}, PackageName)"
   },
   {
    "name": "FlowName",
    "label": "Flow Name",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\"}, FlowName)"
   },
   {
    "name": "StatusCode",
    "label": "Status Code",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\"}, StatusCode)"
   },
   {
    "name": "Result",
    "label": "Result",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\"}, Result)"
   },
   {
    "name": "Initiator",
    "label": "Initiator IP Address",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\"}, InitiatorIpAddress)"
   },
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "CustomFilter", "label": "Custom Filter" }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard provides the information required to analyse the flow execution requests within the Cortex Innovation platform.\r\n\r\n|Filter  |Description|\r\n|--------|-----------|\r\n| Tenant | List of tenants. |\r\n| System | List of systems. |\r\n| Node | List of hosts that processed the requests. |\r\n| Package Name | List of packages. |\r\n| Flow Name | List of flows that have execution requests. |\r\n| Status Code | List of [status codes](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Status_codes) found in the HTTP responses. |\r\n| Result | List of results found in the HTTP responses. |\r\n| Initiator IP Address | List of IP addresses for the initiators of the requests. |\r\n| Interval | List of intervals to perform the time series aggregations upon. This only affects the graphs on this dashboard. |\r\n| Custom Filter | Enables filtering on all available values including those that are not exposed by default. |\r\n\r\nAll filters (excluding Interval and Custom Filter) will display their available options dependant on the preceeding filters selected.\r\n"
     }
    }
   ]
  },
  { "title": "Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "# Overview  \r\nKey flow execution request metrics for the specified time range.  \r\n  \r\n**Note:** The Interval filter does not affect these values."
   }
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Displays the total number of flow execution requests during the specified time range.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} [$__range]))",
     "legendFormat": "Total Requests",
     "resolution": 1
    },
    {
     "expr": "sum(count_over_time({job=\"flows\", RequestStatus=\"Error\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} [$__range]))",
     "legendFormat": "Total Errored Requests"
    }
   ]
  },
  {
   "title": "Total Requests Errored",
   "type": "stat",
   "description": "Displays the total number of flow execution requests that errored during the specified time range.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "targets": [
    { "panelId": 87 }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "stat",
   "description": "Displays the percentage of errored flow execution requests against the total flow execution requests during the specified time range.\n\n| Threshold | Value | Colour |\n|------------------|-----------|------------|\n| OK  | &lt; 5% | green |\n| WARNING |  &gt; 5% | orange |\n| CRITICAL |   &gt; 10% | red |",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "panelId": 87 }
   ]
  },
  {
   "title": "Mean Request Duration",
   "type": "stat",
   "description": "Displays the mean duration in seconds for flow execution requests during the specified time range.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$__range]) by (Api)",
     "legendFormat": "Total Requests",
     "resolution": 1
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "# Requests\r\nFlow execution request history for the specified time range."
   }
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Displays the:\n- count of all flow execution requests\n- mean duration in seconds for all flow execution requests\n\nEach data point value is calculated by aggregating requests based on the Interval filter.  Currently each data point value will be an aggregation of the data for the previous $Interval.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} [$Interval]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "avg by (Type) (avg_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$Interval]))",
     "legendFormat": "Mean Duration (ms)"
    },
    {
     "expr": "min by (Type) (min_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$Interval]))",
     "legendFormat": "Min Duration (ms)"
    },
    {
     "expr": "max by (Type) (max_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$Interval]))",
     "legendFormat": "Max Duration (ms)"
    },
    {
     "expr": "sum(count_over_time({job=\"flows\", Type=\"Cortex\", RequestStatus=\"Error\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} [$Interval]))",
     "legendFormat": "Errored Requests"
    },
    {
     "expr": "avg by (Type) (avg_over_time({job=\"flows\", Type=\"Cortex\", RequestStatus=\"Error\",  Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$Interval]))",
     "legendFormat": "Errored Requests Mean Duration (ms)"
    }
   ]
  },
  {
   "title": "Top 10 Requests by Count",
   "type": "table",
   "description": "Displays the 10 most executed flows during the specified time range with their mean, minimum and maximum duration in seconds.\n\nNote: The Interval filter does not affect this list.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "topk(10, sum by (FlowName) (count_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json [$__range])))",
     "legendFormat": "Top 10 Executions"
    },
    {
     "expr": "bottomk(10, sum by (FlowName) (count_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json [$__range])))",
     "legendFormat": "Bottom 10 Executions"
    },
    {
     "expr": "topk(10, avg by (FlowName) (avg_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$__range])))",
     "legendFormat": "Top 10 Mean Duration (ms)"
    },
    {
     "expr": "bottomk(10, avg by (FlowName) (avg_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$__range])))",
     "legendFormat": "Bottom 10 Mean Duration (ms)"
    },
    {
     "expr": "sum by (FlowName) (count_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json [$__range]))",
     "legendFormat": "Total Count"
    },
    {
     "expr": "sum by (FlowName) (count_over_time({job=\"flows\", Type=\"Cortex\", RequestStatus=\"Error\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json [$__range]))",
     "legendFormat": "Error Count"
    },
    {
     "expr": "avg by (FlowName) (avg_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$__range]))",
     "legendFormat": "Mean Duration (ms)"
    },
    {
     "expr": "min by (FlowName) (min_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$__range]))",
     "legendFormat": "Min Duration (ms)"
    },
    {
     "expr": "max by (FlowName) (max_over_time({job=\"flows\", Type=\"Cortex\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$__range]))",
     "legendFormat": "Max Duration (ms)"
    }
   ]
  },
  {
   "title": "Bottom 10 Requests by Count",
   "type": "table",
   "description": "Displays the 10 least executed flows during the specified time range with their mean, minimum and maximum duration in seconds.\n\nNote: The Interval filter does not affect this list. Also any flows with zero executions will not be displayed.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
   "targets": [
    { "panelId": 97 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 41 },
   "options": {
    "content": "# Errors\r\nErrored flow execution request history for the specified time range."
   }
  },
  {
   "title": "Errored Requests",
   "type": "timeseries",
   "description": "Displays the:\n- count of errored flow execution requests\n- mean duration in seconds for errored flow execution requests \n\nEach data point value is calculated by aggregating requests based on the Interval filter.  Currently each data point value will be an aggregation of the data for the previous $Interval.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 88 }
   ]
  },
  {
   "title": "Top 10 Requests by Error Count",
   "type": "table",
   "description": "Displays the 10 most errored (by status code and result) flows during the specified time range with their mean, minimum and maximum duration in seconds.\n\nNote: The Interval filter does not affect this list.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "topk(10, sum by (FlowName, StatusCode, Result) (count_over_time({job=\"flows\", Type=\"Cortex\", RequestStatus=\"Error\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json [$__range])))",
     "legendFormat": "Top10 Errored Requests"
    },
    {
     "expr": "avg by (FlowName, StatusCode, Result) (avg_over_time({job=\"flows\", Type=\"Cortex\", RequestStatus=\"Error\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$__range]))",
     "legendFormat": "Mean Duration (ms)"
    },
    {
     "expr": "min by (FlowName, StatusCode, Result) (min_over_time({job=\"flows\", Type=\"Cortex\", RequestStatus=\"Error\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$__range]))",
     "legendFormat": "Min Duration (ms)"
    },
    {
     "expr": "max by (FlowName, StatusCode, Result) (max_over_time({job=\"flows\", Type=\"Cortex\", RequestStatus=\"Error\", Api=\"Cortex.ServiceFabric.Service.ApiGateway.Controllers.StartExecutionsController.ExecuteFlowSync\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", PackageName=~\"$PackageName\", FlowName=~\"$FlowName\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$__range]))",
     "legendFormat": "Max Duration (ms)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 68 },
   "options": {
    "content": "# Duration\r\nFlow execution request duration history for the specified time range."
   }
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "Displays the:\n\n- mean duration in seconds for all flow execution requests\n- minimum duration in seconds for all flow execution requests\n- maximum duration in seconds for all flow execution requests\n\nEach data point value is calculated by aggregating requests based on the Interval filter. Currently each data point value will be an aggregation of the data for the previous 5m.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 71 },
   "targets": [
    { "panelId": 88 }
   ]
  },
  {
   "title": "Top 10 Longest Running Requests by Mean Duration",
   "type": "table",
   "description": "Displays the 10 flows with the longest mean duration during the specified time range with their total count, error count, minimum and maximum duration in seconds.\n\nNote: The Interval filter does not affect this list.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 84 },
   "targets": [
    { "panelId": 97 }
   ]
  },
  {
   "title": "Top 10 Shortest Running Requests by Mean Duration",
   "type": "table",
   "description": "Displays the 10 flows with the shortest mean duration during the specified time range with their total count, error count, minimum and maximum duration in seconds.\n\nNote: The Interval filter does not affect this list. Also any flows with zero executions will not be displayed.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 84 },
   "targets": [
    { "panelId": 97 }
   ]
  }
 ]
}