{
 "title": "Platform Health",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Tenant",
    "query": "label_values({job=\"flows\", Type=\"Cortex\"}, Tenant)"
   },
   {
    "name": "System",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\"}, System)"
   },
   {
    "name": "Node",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\"}, Node)"
   },
   {
    "name": "API",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\"}, Api)"
   },
   {
    "name": "StatusCode",
    "label": "Status Code",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\"}, StatusCode)"
   },
   {
    "name": "Result",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\"}, Result)"
   },
   {
    "name": "Initiator",
    "label": "Initiator IP Address",
    "query": "label_values({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\"}, InitiatorIpAddress)"
   },
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "CustomFilter", "label": "Custom Filter" }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard provides the information required to analyse the health of the Cortex Innovation platform.\r\n\r\n|Filter  |Description|\r\n|--------|-----------|\r\n| Tenant | List of tenants. |\r\n| System | List of systems. |\r\n| Node | List of hosts that processed the requests. |\r\n| API | List of the API endpoints found in the HTTP requests. |\r\n| Status Code | List of [status codes](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Status_codes) found in the HTTP responses. |\r\n| Result | List of results found in the HTTP responses. |\r\n| Initiator IP Address | List of IP addresses for the initiators of the requests. |\r\n| Interval | List of intervals to perform the time series aggregations upon. This only affects the graphs on this dashboard. |\r\n| Custom Filter | Enables filtering on all available values including those that are not exposed by default. |\r\n\r\nAll filters (excluding Interval and Custom Filter) will display their available options dependant on the preceeding filters selected.\r\n"
     }
    }
   ]
  },
  { "title": "Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "# Overview  \r\nKey platform health metrics for the specified time range.  \r\n  \r\n**Note:** The Interval filter does not affect these values."
   }
  },
  {
   "title": "Availability",
   "type": "stat",
   "description": "Displays the availability of the platform by calculating the successful requests / total requests during the specified time range.  Successful requests are all requests that do not result in a 5xx HTTP response, 4xx responses are considered successful in this scenario.\n\n| Threshold | Value | Colour |\n|------------------|-----------|------------|\n| OK  | &gt; 95% | green |\n| WARNING |  &gt; 90% | orange |\n| CRITICAL |   &lt; 90% | red |",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} [$__range]))",
     "legendFormat": "Total Requests",
     "resolution": 1
    },
    {
     "expr": "(sum(count_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} |~ \"\\\"StatusCode\\\":.?[1-4,6-9][0-9][0-9]\" [$__range])) or (sum(count_over_time({job=\"flows\"}[$__range])) * 0))",
     "legendFormat": "Total Successfull Requests"
    },
    {
     "expr": "sum(count_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} [1s]))",
     "legendFormat": "Requests / second"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Displays the total number of requests during the specified time range.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "targets": [
    { "panelId": 87 }
   ]
  },
  {
   "title": "Errored Requests",
   "type": "stat",
   "description": "Displays the total number of errored requests during the specified time range.  Errored requests are all requests that result in an unknown or 5xx HTTP response, 4xx responses are considered successful in this scenario.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 87 }
   ]
  },
  {
   "title": "Mean Request Duration",
   "type": "stat",
   "description": "Displays the mean duration for requests during the specified time range.\n\nNote: Certain APIs may take significantly longer than others skewing the result.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} |~ \"\\\"InMs\\\":.?\" | json | unwrap Event_Duration_InMs [$__range]) by (job)",
     "legendFormat": "Mean Duration (ms)",
     "resolution": 1
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "# Availability\r\nThe availability of the Cortex Innovation platform."
   }
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "Displays the availability of the Cortex Innovation Platform by calculating successful requests / total requests. Successful requests are all requests that do not result in a 5xx HTTP response, 4xx responses are considered successful in this scenario.\n\nEach data point value is calculated by aggregating requests based on the Interval filter.  Currently each data point value will be an aggregation of the data for the previous $Interval.  If we have no data for the previous $Interval, the line will be broken as we do not know the availability at this time.\n\n| Threshold | Value | Colour |\n|------------------|-----------|------------|\n| OK  | &gt; 95% | green |\n| WARNING |  &gt; 90% | orange |\n| CRITICAL |   &lt; 90% | red |",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(count_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} |~ \"\\\"StatusCode\\\":.?[1-4,6-9][0-9][0-9]\" [$Interval])) or (sum(count_over_time({job=\"flows\"}[$Interval])) * 0))",
     "legendFormat": "Successful Requests"
    },
    {
     "expr": "(sum(count_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} [$Interval])))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "(sum(count_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} [1s])))",
     "legendFormat": "Requests / second"
    },
    {
     "expr": "(sum(count_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} !~ \"\\\"StatusCode\\\":.?[1-4,6-9][0-9][0-9]\" [$Interval])) )",
     "legendFormat": "Errored Requests"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "# Requests\r\nRequests processed by the Cortex Innovation platform during the specified time range."
   }
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Displays the count of all requests.\n\nEach data point value is calculated by aggregating requests based on the Interval filter.  Currently each data point value will be an aggregation of the data for the previous $Interval.\n\nAlso displays count of all requests per second.\n\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 88 }
   ]
  },
  {
   "title": "Top 10 Responses by Total Count",
   "type": "table",
   "description": "Displays the Top 10 HTTP responses that occured during the specified time range with their mean, minimum and maximum duration in seconds. \n\nNote: The Interval filter does not affect this list.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "topk(10, sum by (StatusCode, Result) (count_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} [$__range])))",
     "legendFormat": "Top10 Responses"
    },
    {
     "expr": "avg by (StatusCode, Result) (avg_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} |~ \"\\\"InMs\\\":.?\" | json | unwrap Event_Duration_InMs [$__range]))",
     "legendFormat": "AvgDuration"
    },
    {
     "expr": "min by (StatusCode, Result) (min_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} |~ \"\\\"InMs\\\":.?\" | json | unwrap Event_Duration_InMs [$__range]))",
     "legendFormat": "MinDuration"
    },
    {
     "expr": "max by (StatusCode, Result) (max_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} |~ \"\\\"InMs\\\":.?\" | json | unwrap Event_Duration_InMs [$__range]))",
     "legendFormat": "MaxDuration"
    },
    {
     "expr": "topk(10, sum by (StatusCode, Result) (count_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} !~ \"\\\"StatusCode\\\":.?[1-4,6-9][0-9][0-9]\" [$__range])))",
     "legendFormat": "Top10 Error Responses"
    },
    {
     "expr": "topk(10, avg by (StatusCode, Result) (avg_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} |~ \"\\\"InMs\\\":.?\" | json | unwrap Event_Duration_InMs [$__range])))",
     "legendFormat": "Top10 Response Durations"
    },
    {
     "expr": "sum by (StatusCode, Result) (count_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} [$__range]))",
     "legendFormat": "Total Count"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
   "options": {
    "content": "# Errors\r\nErrored request history for the specified time range."
   }
  },
  {
   "title": "Errored Requests",
   "type": "timeseries",
   "description": "Displays the:\n- count of errored requests\n- count of all requests\n\nEach data point value is calculated by aggregating requests based on the Interval filter.  Currently each data point value will be an aggregation of the data for the previous $Interval.\n\nErrored requests are all requests that result in an unknown or 5xx HTTP response, 4xx responses are considered successful in this scenario.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 88 }
   ]
  },
  {
   "title": "Top 10 Error Responses by Error Count",
   "type": "table",
   "description": "Displays the Top 10 HTTP error responses that occured during the specified time range with their mean, minimum and maximum duration in seconds. Errored requests are all requests that result in an unknown or 5xx HTTP response, 4xx responses are considered successful in this scenario.\n\nNote: The Interval filter does not affect this list.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 71 },
   "targets": [
    { "panelId": 131 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 83 },
   "options": {
    "content": "# Duration\r\nRequest duration history for the specified time range.\r\n\r\nNote: Certain APIs may take significantly longer than others skewing the results."
   }
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "Displays the:\n\n- mean duration in seconds for all requests\n- minimum duration in seconds for all requests\n- maximum duration in seconds for all requests\n\nEach data point value is calculated by aggregating requests based on the Interval filter. Currently each data point value will be an aggregation of the data for the previous 5m.\n\nNote: Certain APIs may take significantly longer than others skewing the result.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "(avg by (job) (avg_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$Interval])) )",
     "legendFormat": "Average Duration in ms"
    },
    {
     "expr": "(min by (job) (min_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$Interval])) )",
     "legendFormat": "Min Duration in ms"
    },
    {
     "expr": "(max by (job) (max_over_time({job=\"flows\", Type=\"Cortex\", Tenant=~\"$Tenant\", System=~\"$System\", Node=~\"$Node\", Api=~\"$API\", StatusCode=~\"$StatusCode\", Result=~\"$Result\", InitiatorIpAddress=~\"$Initiator\"} | json | unwrap Event_Duration_InMs [$Interval])) )",
     "legendFormat": "Max Duration in ms"
    }
   ]
  },
  {
   "title": "Top 10 Responses by Mean Duration",
   "type": "table",
   "description": "Displays the top 10 HTTP responses that occured during the specified time range with their mean, minimum and maximum duration in seconds. \n\nNote: The Interval filter does not affect this list. Also, certain APIs may take significantly longer than others skewing the result.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 99 },
   "targets": [
    { "panelId": 131 }
   ]
  }
 ]
}